name: via
description: "Voice Interactive Assistant - A Flutter app for voice-controlled document management and accessibility."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.8.1







dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8

  
  flutter_riverpod: ^2.6.1

  
  go_router: ^15.2.4

  
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.6.0

  
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3

  
  pdf: ^3.11.3
  pdfx: ^2.9.2
  file_picker: ^10.2.0

  
  intl: ^0.20.2

  
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  permission_handler: ^12.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

  
  flutter_screenutil: ^5.9.3
  supabase_flutter: ^2.9.1

  
  http: ^1.2.0
  flutter_local_notifications: ^19.3.0
  workmanager: ^0.7.0
  record: ^6.0.0

  
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0

  
  
  

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0

  
  mockito: ^5.4.4
  build_runner: ^2.4.8





flutter:

  
  
  
  uses-material-design: true

  
  generate: true

  
  assets:
    - assets/images/
    - assets/icons/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
